name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      boolean_default_true:
        description: 'Test scenario tags'
        required: false
        type: boolean
        default: true
      boolean_default_false:
        required: false
        type: boolean
        default: 'false'

env:
  LOG_LEVEL: ${{ inputs.logLevel }}

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      volumes:
        - maven-cache:/root/.m2
    steps:
      - run: env
