name: Docker Image CI

on: 
  - push
  - workflow_dispatch

env:
  LOG_LEVEL: ${{ inputs.logLevel }}

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      volumes:
        - maven-cache:/root/.m2
    steps:
      - run: env
